name: Weekly Report - Checklist Issues (Opened and closed)

on:
  workflow_dispatch:
  schedule:
    - cron: "59 23 * * 0" # Every Sunday at 23:59
  
env:
    GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    USER: arnaums02
    PROJECT: Joint-Project---Grup-B

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: pip install PyGithub pandas matplotlib -q

    - name: Ejecutar script Python
      run: |
        python generate_weekly_checklist.py
        
    - name: Subir imagen generada
      uses: actions/upload-artifact@v2
      with:
        name: checklist_weekly
        path: checklist_weekly.png
