name: Django Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo apt-get install -y libnss3
        sudo apt-get install -y libgconf-2-4
        sudo apt-get install -y libxss1
        sudo apt-get install -y libappindicator1
        sudo apt-get install -y fonts-liberation
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run tests
      env:
        DATABASE_URL: postgres://user:password@127.0.0.1:5432/test_db
      run: |
        python manage.py migrate
        python manage.py test
